#ifndef LIBELECTRONICBADGE_GLOBAL_H
#define LIBELECTRONICBADGE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBELECTRONICBADGE_LIBRARY)
#define LIBELECTRONICBADGE_EXPORT Q_DECL_EXPORT
#else
#define LIBELECTRONICBADGE_EXPORT Q_DECL_IMPORT
#endif

#define MGSKJ_ELECTRONIC_BADGE 1

#endif  // LIBELECTRONICBADGE_GLOBAL_H
